#!/bin/bash

#--------------------------------------------
# 功能：Xcode项目Build号加1
#--------------------------------------------

if [ ! -d $1 ];then
	echo "Error! The first param must be a directory."
	exit 2
fi

#工程绝对路径
if [ ! $1 ]; then
	project_path=$(cd `dirname $0`; pwd)
else 
	cd $1
	project_path=$(pwd)
fi

#工程target路径
# target_path=$(echo ${project_path}/*.xcodeproj | awk -F. '{print $1}')
#plist文件路径
# infoplist_path=$target_path/*nfo.plist
infoplist_path=${PRODUCT_SETTINGS_PATH}
#取版本号
bundleShortVersion=$(/usr/libexec/PlistBuddy -c "print CFBundleShortVersionString" ${infoplist_path})
#取build值
bundleVersion=$(/usr/libexec/PlistBuddy -c "print CFBundleVersion" ${infoplist_path})
#取displayName
displayName=$(/usr/libexec/PlistBuddy -c "print CFBundleDisplayName" ${infoplist_path})
#build值加1
newbundleVersion=$(($bundleVersion+1))

if [ ! -n "$newbundleVersion" ]; then
	newbundleVersion=$(($bundleShortVersion+1))
	if [! -n "$newbundleVersion" ]; then
		echo ""
		echo "------ BuildVersion ${bundleVersion} Add 1 Faild !!!!!!"
		echo ""
	else
		/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $newbundleVersion" ${infoplist_path}
		echo "$displayName CFBundleShortVersionString:$bundleShortVersion"
		echo "      ↓↓↓↓↓↓ + 1 ↓↓↓↓↓↓"
		echo "$displayName CFBundleShortVersionString:$newbundleVersion"
		echo ""

		customBuild=$(/usr/libexec/PlistBuddy -c "print CustomBuild" ${infoplist_path})
		if [ -n "$customBuild" ]; then
			/usr/libexec/PlistBuddy -c "Set :CustomBuild $newbundleVersion" ${infoplist_path}
			echo "$displayName CustomBuild:$customBuild"
			echo "      ↓↓↓↓↓↓ + 1 ↓↓↓↓↓↓"
			echo "$displayName CustomBuild:$newbundleVersion"
			echo ""
		fi
	fi
else
	/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $newbundleVersion" ${infoplist_path}
	echo ""
	echo "$displayName BuildVersion:$bundleVersion"
	echo "      ↓↓↓↓↓↓ + 1 ↓↓↓↓↓↓"
	echo "$displayName BuildVersion:$newbundleVersion"
	echo ""
fi
