#!/bin/bash

#--------------------------------------------
# 功能：ipa 替换图片资源
# 使用说明：
#			ipa-img-replace <ipa directory> [-i <img file directory>] [-o <ipa output directory>]
#
# 参数说明：	-i imgfile_path			图片资源路径
#			-o output_path			ipa文件输出的文件夹（必须为已存在的文件路径）默认为原ipa路径下
#--------------------------------------------

echo ""

if [ ! $1 ];then
	project_path=$(cd `dirname $0`; pwd)
	ipa_path=$(echo ${project_path}/*.ipa)
else 
	ipa_path=$1
	if [ ! -f "$ipa_path" ]; then
		echo "------ Error! $ipa_path not exist!"
		exit 2
	elif [ ${ipa_path##*.} != ipa ]; then
		echo "------ Error! $ipa_path must be an ipa directory!"
		exit 2
	fi
	project_path=$(dirname "$ipa_path")
fi

#文件是否存在
if [ ! -f "$ipa_path" ]; then
	echo "------ Error! Ipa not exist in $project_path!"
	exit 2
elif [ ${ipa_path##*.} != ipa ]; then
	echo "------ Error! $ipa_path must be an ipa directory!"
	exit 2
fi

#输出文件名
ipa_name=replaced_$(basename "${ipa_path}")

embedded_path=""
param_pattern="i:o:"
OPTIND=2
while getopts $param_pattern optname
  do
    case "$optname" in       
	  
	  "i")
		tmp_optind=$OPTIND
		tmp_optname=$optname
		tmp_optarg=$OPTARG

		OPTIND=$OPTIND-1
		if getopts $param_pattern optname ;then
			echo  "Error argument value for option $tmp_optname"
			exit 2
		fi
		OPTIND=$tmp_optind

		if [ -d "$tmp_optarg" ]; then
			imgfile_path="${tmp_optarg}"
		else
			echo "Error!The value of option i must be an exist directory."
			exit 2
		fi
		;;
      "o")
		tmp_optind=$OPTIND
		tmp_optname=$optname
		tmp_optarg=$OPTARG

		OPTIND=$OPTIND-1
		if getopts $param_pattern optname ;then
			echo  "Error argument value for option $tmp_optname"
			exit 2
		fi
		OPTIND=$tmp_optind

		if [ -d "$tmp_optarg" ];then
			cd "$tmp_optarg"
			output_path=$(pwd)
			cd ${1%/*}
		else
			if [ "${tmp_optarg##*.}" == "ipa" ]; then
				output_path=$(dirname "${tmp_optarg}")
				ipa_name=$(basename "${tmp_optarg}")
				cd ${1%/*}
			else
				echo "Error!The value of option o must be an exist directory or a ipa."
				exit 2
			fi
		fi

        ;;
	  "?")
        echo "Error! Unknown option $OPTARG"
		exit 2
        ;;
      ":")
        echo "Error! No argument value for option $OPTARG"
		exit 2
        ;;
      *)
      # Should not occur
        echo "Error! Unknown error while processing options"
		exit 2
        ;;
    esac
  done

#解压ipa
cd "${project_path}"
unzip -o "${ipa_path}"
if [ $? -ne 0 ];then
    #解压不成功
    echo "#############		INSTALL UNZIP COMMAND	#############"
    sudo apt-get install unzip
    unzip -o "${ipa_path}"
fi  


#app路径
app_path=$(echo ${project_path}/Payload/*.app)

#定制区域
# - 替换图片资源
if [ -d "$imgfile_path" ];then
	while IFS= read -r -d $'\0' dir; do
		imgname=$(basename $dir)
		imgpath=$dir
		while IFS= read -r -d $'\0' dir; do
			cp $imgpath $dir
		done < <(find $app_path -type f -iname $imgname -depth -print0)
	done < <(find "$imgfile_path" -type f -iname "*.png" -depth -print0)
else
	exit
fi

#收尾
zip -qr "${ipa_name}" Payload
if [ $? -ne 0 ];then
    #压缩不成功
    echo "#############		INSTALL ZIP COMMAND	#############"
    sudo apt-get install zip
    zip -qr "${ipa_name}" Payload
fi  
rm -rf "${project_path}"/Payload
if [ -d "${project_path}/__MACOSX" ]; then
	rm -rf "${project_path}"/__MACOSX
fi

if [ -d "$output_path" ];then
	
	cd "${output_path}"
	if [ "$(pwd "${output_path}")" == "${project_path}" ]; then
		exit 2
	fi

	cp "${project_path}/${ipa_name}" "$output_path"/"${ipa_name}"
	rm -rf "${project_path}/${ipa_name}"
	echo ""
	echo "Copy ipa file successfully to the path $output_path/${ipa_name}"
fi

echo ""
