#!/bin/bash

rm -r out/

_AppBundleIdentifier="com.nationsky.test"
_EMMNSCiSDKAppKey="81157488a90c14509d35a97e05b71cea"
_EMMSDKAppKey="fbfb7daac9f00c82c3550db8844dcff4"

cp -r $(pwd)/*.ipa $(pwd)/nationsky_back.ipaback
unzip $(pwd)/*.ipa
/usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier ${_AppBundleIdentifier}" $(pwd)/Payload/*.app/Info.plist
/usr/libexec/PlistBuddy -c "Set :EMMNSCiSDKAppKey ${_EMMNSCiSDKAppKey}" $(pwd)/Payload/*.app/Info.plist
/usr/libexec/PlistBuddy -c "Set :EMMSDKAppKey ${_EMMSDKAppKey}" $(pwd)/Payload/*.app/Info.plist
/usr/libexec/PlistBuddy -c "Set :CertificateValidation false" $(pwd)/Payload/*.app/Info.plist
rm -r $(pwd)/*.ipa

zip -r nationsky_test.ipa Payload/

rm -r Payload/

./AppReSign $(pwd)/*.ipa  -AppBundleIdentifier="com.nationsky.test" -ProvisionProfilePath="$(pwd)/*.mobileprovision" -Certificate="4566FC00FD31331BF4B40C6A479B5E089C7EB11A" -Out="$(pwd)/out" -ResourceRules="$(pwd)/ResourceRules.plist"
